### ISSUE TITLE
Report Error when using docker to predict and save output files

### ISSUE THREAD

**Issue by jijun-cheng** [TissueImageAnalytics/CoNIC#11]
Hi TIA Group,

Thank you for holding such an amazing challenge!

I  have trained the network and prepared to submit according to the `docker-template` branch. As you showed in the video, I successfully used the non docker local environment to get its output.
![image-20220216004732806](https://user-images.githubusercontent.com/55268529/154126599-4897eeee-b4a2-4c79-a022-36981d8ed900.png)

 After that, I successfully created the docker container and put `execute_ IN_ Docker = true` modify   `LOCAL_INPUT` and `LOCAL_ OUTPUT` in `test.sh`.  However, I encountered some difficulties. Docker uses GPU and completes infering. 

However, an error occurred while saving the output. The output log is as follows:
What is the reason for this? How can I solve this problem?

Best regards!

P.S. I used Ubuntu18.04 and I have tried to switch to root and execute `sudo ./test.sh` ,  but the above error is still encountered.

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```
Successfully tagged conic-inference:latest
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.

Working Directory: /opt/algorithm

>>>>>>>>>>>>>>>>> Start User Script

INPUT_DIR: /input/
-/input/
--F-/input/images.mha
USER_DATA_DIR:  ['hovernet-conic.pth', 'net_epoch=50.tar']
-/opt/algorithm/data/
--F-/opt/algorithm/data/hovernet-conic.pth
--F-/opt/algorithm/data/net_epoch=50.tar
OUTPUT_DIR: /output/
CUDA: True
---Device 0: GeForce RTX 3080 Ti
---Device 1: GeForce RTX 3080 Ti
/opt/algorithm/data//net_epoch=50.tar
Process Batch: 100%|##############################| 4/4 [00:04<00:00,  1.17s/it]Infer time:  7.805699825286865

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/algorithm/process.py", line 35, in <module>
    run(**ENTRY)
  File "/opt/algorithm/source/main.py", line 203, in run
    f"{OUT_DIR}/pred_seg.mha"
  File "/home/algorithm/.local/lib/python3.7/site-packages/itk/support/extras.py", line 848, in imwrite
    writer.Update()
RuntimeError: /work/ITK-source/ITK/Modules/IO/Meta/src/itkMetaImageIO.cxx:1128:
ITK ERROR: MetaImageIO(0x555dd7b28080): File cannot be written: /output///pred_seg.mha
Reason: Permission denied
```

**Comment by jijun-cheng** [comment]
I used Ubuntu18.04 and I have tried to switch to root and execute `sudo ./test.sh` ,  but the above error is still encountered.

**Comment by jijun-cheng** [comment]
The problem has been solved.
